### ISSUE TITLE
Fatal Erro

### ISSUE THREAD

**Issue by XavRsl** [arandilopez/laravel-feed-parser#1]
Hello !
Could you help me on that one ? I'm using Lumen. I get : 

```
PHP Fatal error:  Call to a member function make() on null in /var/www/apogee-site/vendor/illuminate/support/Facades/Facade.php on line 210
```

I followed your configuration exemple, still can't find out what I'm doing wrong...

Thanks

**Comment by XavRsl** [comment]
Works when using $app->feed->make()

**Comment by arandilopez** [comment]
Thanks @XavRsl, let me check it out.

**Comment by arandilopez** [comment]
@XavRsl to enable facades you have to uncomment the line `$app->withFacades();` in `bootstrap/app.php`... Otherwise you will have that error. I will add it to README. Thanks for your help. :+1:

**Comment by XavRsl** [comment]
Thanks for coming back to me. I must admit I'm new to Lumen. I've had a look at the docs but they're not nearly as complete as Laravel's.

It's working now. Good job by the way ! Thanks again.
