### ISSUE TITLE
get_item_tags on SimplePieAdapter

### ISSUE THREAD

**Issue by alberto-bottarini** [arandilopez/laravel-feed-parser#2]
Hi, using your library, I found that your SimplePieItemAdapter does not implements all the method that are available on "original" SimplePie_Item.

For example I noticed that is it impossible to call get_item_tags to retrieve custom namespaced tag. 

It will be great if you could implement this feature.

Thanks

**Comment by arandilopez** [comment]
Hi @alberto-bottarini thanks for comment. Did you try with $item->itemTags ???
The object must to map with get_item_tags(), you will receive the raw tags from SimplePie Item object

**Comment by alberto-bottarini** [comment]
I tried but it does not work because get_item_tags is a method that needs parameters.
I solved using getRawItem()->get_item_tags() but it's a cheat :)

Thanks for response.

**Comment by arandilopez** [comment]
So, would be better a call_user_func...? Or implement that??
