### ISSUE TITLE
Error en Providers

### ISSUE THREAD

**Issue by carlosjac** [arandilopez/laravel-feed-parser#4]
Hola Arandi

Intenté usar este paquete con Lumen 5.2.

Es necesario corregir los archivos /src/Providers/FeedServiceProvider.php y /src/Providers/LumenFeedServiceProvider.php

En ambos archivos llamas al método bindShared.  Ese método ya no existe en 5.2.
Debes llamar al método bind, y pasar un parámetro adicional en true.  De ese modo, obtienes lo mismo que con bindShared pero compatible con Lumen 5.2.
gracias!
Carlos

**Comment by arandilopez** [comment]
Hola @carlosjac, ese asunto esta sobre master ahora, dejame hacer un tag para que puedas actualizar
